// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeaxotolnqqovrxejfjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYXhvdG9sbnFxb3ZyeGVqZmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDA2MDIsImV4cCI6MjA2OTk3NjYwMn0.52N_03zJt5yOffIh_JMzVT3WpnLsApzzRKgFaSrYm04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});